bashmycode/urls.py
from django.urls import path, reverse
from .views import PostListViewHelp, PostListViewBash, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView
from bashmycode import views
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

app_name = 'bashmycode'

urlpatterns = [
    path('', views.index, name='index'),
    
    path('help/', views.help, name='help'),
    path('register/', views.register, name='register'),

    path('login/', auth_views.LoginView.as_view(template_name='bashmycode/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='bashmycode/logout.html'), name='logout'),

    path('profile/', views.profile, name='profile'),

    path('bash/', PostListViewBash.as_view(), name='bash'),
    path('help/', PostListViewHelp.as_view(), name='help'),

    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

	path('like_post/', views.LikePostView.as_view(), name='like_post'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wad2_group_project/urls.py
from django.contrib import admin
from django.urls import path, include
from bashmycode import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Maps any URL starting with bashmycode/ to be handled by bashmycode
    path('', views.index, name='index'),
    path('bashmycode/', include('bashmycode.urls')),
    
    # Password reset links
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset_form.html'), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'), name='password_reset_complete'),

    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bashmycode/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username}\'s Profile'
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


class Post(models.Model):
    POST_CHOICES = [
        ('HELP', 'HELP'),
        ('BASH', 'BASH'),
    ]
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    post_type = models.CharField(max_length=4, blank=False, choices=POST_CHOICES)

    likes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('bashmycode:post-detail', kwargs={'pk': self.pk})

bashmycode/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

bashmycode/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from .models import Post
from django.contrib.auth.decorators import login_required
from django.views import View
from django.http import HttpResponse



def index(request):
    return render(request, 'bashmycode/index.html')

class PostListViewBash(ListView):
    model = Post
    queryset = Post.objects.filter(post_type='BASH').order_by('-likes')
    template_name = 'bashmycode/bash.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 5

# SOMETHING WRONG WITH PAGINATION ON HELP
class PostListViewHelp(ListView):
    model = Post
    queryset = Post.objects.filter(post_type='HELP').order_by('-likes')
    template_name = 'bashmycode/help.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 5


class UserPostListView(ListView):
    model = Post
    template_name = 'bashmycode/user_posts.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-likes')

class PostDetailView(DetailView):
    model = Post

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'post_type']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'post_type']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/bashmycode/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class LikePostView(View):
    def get(self, request):
        post_id = request.GET['post_id']
        try:
            post = Post.objects.get(id=int(post_id))
        except Post.DoesNotExist:
            return HttpResponse(-1)
        except ValueError:
            return HttpResponse(-1)
        post.likes = post.likes + 1
        post.save()
        
        return HttpResponse(post.likes)


def bash(request):
    context = {
        'posts': Post.objects.filter(post_type='BASH').order_by('-date_posted')
    }
    return render(request, 'bashmycode/bash.html', context)

def help(request):
    context = {
        'posts': Post.objects.filter(post_type='HELP').order_by('-date_posted')
    }
    return render(request, 'bashmycode/bash.html', context)
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('/bashmycode/login')
    else:
        form = UserRegisterForm()
    return render(request, 'bashmycode/register.html', {'form': form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('/bashmycode/profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'bashmycode/profile.html', context)

templates/bashmycode/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <link rel="icon" href="{% static 'images/favicon.ico' %}">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        
        <!-- Custom styles for this template -->
        <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">

        <!-- Custom CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'bashmycode/main.css' %}">

        {% if title %}
            <title>BashMyCode - {{ title }}</title>
        {% else %}
            <title>BashMyCode</title>
        {% endif %}

    </head>
    
    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-2">
                <a class="navbar-brand p-4" href="{% url 'bashmycode:index' %}">bashmycode</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'bashmycode:help' %}">Help</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'bashmycode:bash' %}">Bash</a></li>

                        {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'bashmycode:post-create' %}">New Post</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'bashmycode:profile' %}">Profile</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'bashmycode:logout' %}">Log Out</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'bashmycode:login' %}">Log In</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'bashmycode:register' %}">Sign Up</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>
        {% block content %}{% endblock content %}


        <div class="container-fluid">
            <div class="row">
                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                        {% endfor %}
                    {% endif %}
                    
                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2020 BashMyCode &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>
        
        
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/bash-ajax.js' %}" crossorigin="anonymous"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

templates/bashmycode/bash.html
{% extends 'bashmycode/base.html' %}
{% load static %}

{% block content %}
    <h2>BashMyCode</h2>
    {% for post in posts %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}"/>
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'bashmycode:user-posts' post.author.username %}">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'bashmycode:post-detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content"><pre><code>{{ post.content }}</code></pre></p>

                <div>
                    <strong id="like_count">{{ post.likes }}</strong> likes
                </div>

            </div>
        </article>
    {% endfor %}


    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
{% endblock content %}

templates/bashmycode/help.html
{% extends 'bashmycode/base.html' %}
{% load static %}

{% block content %}
    <h2>HelpMyCode</h2>
    {% for post in posts %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}"/>
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'bashmycode:user-posts' post.author.username %}">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'bashmycode:post-detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content"><pre><code>{{ post.content }}</code></pre></p>
            </div>
        </article>
    {% endfor %}
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
{% endblock content %}

templates/bashmycode/index.html
{% extends 'bashmycode/base.html' %}
{% block content %}
    <style>
      * {
        box-sizing: border-box;
      }

      .column {
        float: left;
        width: 50%;
        padding: 15%;
        height: 700px; 
      }
      .row{
          height:100%;
      }
      .row:after {
        content: "";
        display: table;
        clear: both;
      }

      @media screen and (max-width: 600px) {
        .column {
          width: 100%;
        }
      }
    </style>
    <div class="row">
        <div class="column" style="background-color:#ff0000;">
            <center><h2><a class="nav-link" href="{% url 'bashmycode:bash' %}">BashMyCode</a></h2></center>
            <center>
                <strong>
                  Enter "BashMyCode" if you want humor related to
                  coding fails, and basically just a bit of a timewaster
                  and a laugh, not to be taken seriously!
                </strong>
            </center>
        </div>
        <div class="column" style="background-color:#ccebff;">
            <center><h2><a class="nav-link" href="{% url 'bashmycode:help' %}">HelpMyCode</a></h2></center>
            <center>
                <strong>
                  Enter "HelpMyCode" if you need help with improving your coding style/
                  fixing errors that you have. No bullying is allowed in this page.
                </strong>
            </center>
        </div>
    </div>
{% endblock content %}       

templates/bashmycode/login.html
{% load crispy_forms_tags %}
{% load static %}
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'bashmycode/main.css' %}">
        <title>BashMyCode | Login</title>
    </head>
    <body>
        {% block content %}
            <div class="login-clean">
                <form method="POST">
                    <h2 class="sr-only">Login Form</h2>
                    {% csrf_token %}
                    <div class="illustration"><i class="fa fa-code"></i></div>
                    {{ form|crispy }}
                    <div class="form-group">
                        <button class="btn btn-primary btn-block" type="submit">Log In</button>
                    </div>
                    <a class="forgot" href="{% url 'password_reset' %}">Forgot your password?</a>
                    <a class="forgot" href="{% url 'bashmycode:register' %}">Sign Up</a>
                </form>
            </div>
        {% endblock content %}
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    </body>
</html>

templates/bashmycode/logout.html
{% extends "bashmycode/base.html" %}

{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a class="ml-2" href="{% url 'bashmycode:login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

templates/bashmycode/post_confirm_delete.html
{% extends "bashmycode/base.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete this post? "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'bashmycode:post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

templates/bashmycode/post_detail.html
{% extends 'bashmycode/base.html' %}

{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}"/>
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'bashmycode:user-posts' object.author.username %}">{{ object.author }}</a>
                <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
                {% if object.author == user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'bashmycode:post-update' object.id %}">Update</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'bashmycode:post-delete' object.id %}">Delete</a>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title">{{ object.title }}</h2>

            <p class="article-content"><pre><code>{{ object.content }}</code></pre></p>

            <div>
                <strong id="like_count">{{ post.likes }}</strong> likes
                {% if user.is_authenticated %}
                <button id="like_btn"
                        data-postid="{{ post.id }}"
                        class="btn btn-primary btn-sm"
                        type="button">
                    <span data-feather="thumbs-up"></span>
                    Like Post
                </button>
                {% endif %}
            </div>

        </div>
    </article>
{% endblock content %}

templates/bashmycode/post_form.html
{% extends "bashmycode/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>  
        </form>
    </div>
{% endblock content %}

templates/bashmycode/profile.html
{% extends "bashmycode/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
            <div class="media-body">
                <h2 class="account-heading">{{ user.username }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="">Profile Info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>  
        </form>
    </div>
{% endblock content %}

templates/bashmycode/register.html
{% load crispy_forms_tags %}
{% load static %}
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'bashmycode/main.css' %}">
        <title>BashMyCode | Register</title>
    </head>
    <body>
        {% block content %}
            <div class="login-clean">
                <form method="POST">
                    <h2 class="sr-only">Sign Up</h2>
                    {% csrf_token %}
                    <div class="illustration"><i class="fa fa-code"></i></div>
                    {{ form|crispy }}
                    <div class="form-group">
                        <button class="btn btn-primary btn-block" type="submit">Sign Up</button>
                    </div>
                    <a class="forgot" href="{% url 'bashmycode:login' %}">Sign In</a>
                </form>
            </div>
        {% endblock content %}
        <script src="assets/js/jquery.min.js"></script>
        <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    </body>
</html>

templates/bashmycode/user_posts.html
{% extends 'bashmycode/base.html' %}
{% block content %}
    <h2 class="mb-3">Posts by {{ view.kwargs.username }} ({{ page_obj.paginator.count }})</h2>
    {% for post in posts %}
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}"/>
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{% url 'bashmycode:user-posts' post.author.username %}">{{ post.author }}</a>
                    <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'bashmycode:post-detail' post.id %}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>

                <div>
                    <strong id="like_count">{{ post.likes }}</strong> likes

                </div>
            </div>
        </article>
    {% endfor %}
    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}
    {% endif %}
{% endblock content %}